language: android
jdk:
  - openjdk7

android:
  components:

    - build-tools-22.0.1
    - android-23

notifications:
  email: true

cache: false

sudo: false

install:

  - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v

script:
  - ./gradlew clean assembleDebug

